<a href="https://colab.research.google.com/github/NathanMagno/energy-consumers-data/blob/main/cp04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sb
import pandas as pd

Convertendo o dataset em um dataframe pandas

In [ ]:
df = pd.read_csv("household_power_consumption.txt", sep=";", low_memory=False)

1 - Mostrando as 10 primeiras linhas do data frame

In [ ]:
df.head(10)

2 - A Global_active_power é a potência que realiza trabalho útil, convertida em calor, luz ou movimento pelos aparelhos, é o que você paga na conta de luz. Já a Global_reactive_power é a energia que circula em equipamentos como motores e transformadores para criar campos necessários ao seu funcionamento, mas não realiza trabalho útil diretamente. Ou seja, potência ativa faz o trabalho, enquanto a reativa é um suporte para certas cargas.

3 - Valores faltantes

In [ ]:
df.isna().sum()

Date                         0
Time                         0
Global_active_power          0
Global_reactive_power        0
Voltage                      0
Global_intensity             0
Sub_metering_1               0
Sub_metering_2               0
Sub_metering_3           25979
dtype: int64

4 - Conversão de date para DateTime

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')
df['Day_of_Week'] = df['Date'].dt.day_name()
display(df.head())

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Day_of_Week
0,2006-12-16,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0,Saturday
1,2006-12-16,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0,Saturday
2,2006-12-16,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0,Saturday
3,2006-12-16,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0,Saturday
4,2006-12-16,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0,Saturday

5 - Filtrar registros e calculo de média

In [ ]:
''' filtre os regristros apenas do ano de 2007  '''
df_2007 = df[df['Date'].dt.year == 2007]
df_2007

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Day_of_Week
21996,2007-01-01,00:00:00,2.580,0.136,241.970,10.600,0.000,0.000,0.0,Monday
21997,2007-01-01,00:01:00,2.552,0.100,241.750,10.400,0.000,0.000,0.0,Monday
21998,2007-01-01,00:02:00,2.550,0.100,241.640,10.400,0.000,0.000,0.0,Monday
21999,2007-01-01,00:03:00,2.550,0.100,241.710,10.400,0.000,0.000,0.0,Monday
22000,2007-01-01,00:04:00,2.554,0.100,241.980,10.400,0.000,0.000,0.0,Monday
...,...,...,...,...,...,...,...,...,...,...
547591,2007-12-31,23:55:00,1.746,0.204,242.410,7.200,0.000,0.000,18.0,Monday
547592,2007-12-31,23:56:00,1.732,0.210,242.420,7.200,0.000,0.000,18.0,Monday
547593,2007-12-31,23:57:00,1.732,0.210,242.500,7.200,0.000,0.000,18.0,Monday
547594,2007-12-31,23:58:00,1.684,0.144,242.180,7.000,0.000,0.000,18.0,Monday
547595,2007-12-31,23:59:00,1.628,0.072,241.790,6.600,0.000,0.000,18.0,Monday

In [ ]:
df['Global_active_power'] = pd.to_numeric(df['Global_active_power'], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 10 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   datetime64[ns]
 1   Time                   object
 2   Global_active_power    float64
 3   Global_reactive_power  object
 4   Voltage                object
 5   Global_intensity       object
 6   Sub_metering_1         object
 7   Sub_metering_2         object
 8   Sub_metering_3         float64
 9   Day_of_Week            object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 158.3+ MB